install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive
    - /tmp/fontspec-test-fonts

script:
 - l3build check -H --shuffle --first 0-pkg-load || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )
